export const SET_USER_ACCESS_TOKEN = 'SET_USER_ACCESS_TOKEN';

export const SET_USER_ID = 'SET_USER_ID';

export const SET_USER_NAME = 'SET_USER_NAME';

export const SET_USER_ACCESS_TOKEN_DATE = 'SET_USER_ACCESS_TOKEN_DATE';

export const VALIDATE_USER_ACCESS_TOKEN = 'VALIDATE_USER_ACCESS_TOKEN';

export const REQUEST_USER_ACCESS_TOKEN = 'REQUEST_USER_ACCESS_TOKEN';

export const REVOKE_USER_ACCESS_TOKEN = 'REVOKE_USER_ACCESS_TOKEN';

export const GET_USER_FOLLOWS = 'GET_USER_FOLLOWS';

export const GET_STREAMS = 'GET_STREAMS';

export const GET_USERS = 'GET_USERS';

export const REQUEST_CHANNEL_PLAYLIST = 'REQUEST_CHANNEL_PLAYLIST';

export const REQUEST_STREAM_INFO = 'REQUEST_STREAM_INFO';

export const SET_APP_LOADING = 'SET_APP_LOADING';

export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE';

export const REMOVE_CHAT_MESSAGE = 'REMOVE_CHAT_MESSAGE';

export const CLEAR_CHAT = 'CLEAR_CHAT';

export const REQUEST_CHAT_EMOTES = 'REQUEST_CHAT_EMOTES';

export const SET_PLAYER_VOLUME = 'SET_PLAYER_VOLUME';

export const SET_PLAYER_AUDIO_COMPRESSOR = 'SET_PLAYER_AUDIO_COMPRESSOR';

export const TOGGLE_PLAYER_LAYOUT = 'TOGGLE_PLAYER_LAYOUT';

export const SET_IRC_USERSTATE = 'SET_IRC_USERSTATE';

export const CONNECT_USER_TO_IRC = 'CONNECT_USER_TO_IRC';

export const DISCONNECT_USER_FROM_IRC = 'DISCONNECT_USER_FROM_IRC';

export const JOIN_CHANNEL_CHAT = 'JOIN_CHANNEL_CHAT';

export const LEAVE_CHANNEL_CHAT = 'LEAVE_CHANNEL_CHAT';

export const SEND_PLAYER_STATS = 'SEND_PLAYER_STATS';

export const TOGGLE_APP_SETTINGS = 'TOGGLE_APP_SETTINGS';

export const TOGGLE_APP_SETTING = 'TOGGLE_APP_SETTING';

export const TOGGLE_PLAYER_SIDEBAR = 'TOGGLE_PLAYER_SIDEBAR';

export const TOGGLE_PLAYER_CHAT = 'TOGGLE_PLAYER_CHAT';

export const SET_CHAT_PAUSE = 'SET_CHAT_PAUSE';

export const SET_CHAT_WIDTH = 'SET_CHAT_WIDTH';

export const SET_CHAT_HEIGHT = 'SET_CHAT_HEIGHT';

export const SET_APP_COLOR_SCHEME = 'SET_APP_COLOR_SCHEME';

export const SET_APP_LOCALE = 'SET_APP_LOCALE';

export const SET_APP_INTERFACE_SIZE = 'SET_APP_INTERFACE_SIZE';

export const SEARCH_CHANNELS = 'SEARCH_CHANNELS';

export const SET_SIDEBAR_WIDTH = 'SET_SIDEBAR_WIDTH';

export const SET_LIBRARY_SORTING = 'SET_LIBRARY_SORTING';

export const SET_STREAMS = 'SET_STREAMS';

export const SET_FOLLOWED = 'SET_FOLLOWED';

export const SET_USERS = 'SET_USERS';

export const SET_STREAM_DATA = 'SET_STREAM_DATA';

export const SET_ALWAYS_ON_TOP = 'SET_ALWAYS_ON_TOP';

export const RESET_LIBRARY = 'RESET_LIBRARY';
